DB_URL=jdbc:mysql://localhost:3306/studydocs_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
DB_USERNAME=root
DB_PASSWORD=12345

JWT_SECRET=mySecretKey123456789012345678901234567890123456789012345678901234567890

MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USERNAME=ngochinam2005@gmail.com
MAIL_PASSWORD=vkovtpolzalmlzwm

MINIO_ENDPOINT=http://localhost:9000
MINIO_ACCESS_KEY=minioadmin
MINIO_SECRET_KEY=minioadmin
MINIO_BUCKET_NAME=studydocs-documents

REDIS_HOST=localhost
REDIS_PORT=6379

ELASTICSEARCH_URIS=http://localhost:9200
